---
# the ini creation task
- name: creating the {{ filename }} configuration file
  template:
    src: ansible-automation/templates/ini-configuration.j2
    dest: "{{ destination }}"
    mode: "{{ mode | default(0644) }}"
    owner: "{{ owner | default(ansible_user) }}"
    group: "{{ group | default(omit) }}"
